### ISSUE TITLE
[feat] cache the built core metadata so a tree's metadata is built once

### ISSUE THREAD

**Issue by stanislavlevin** [stanislavlevin/pyproject_installer#167]
The `metadata` and `metadata_extra` sources collect a project's dependencies from its built core metadata, which runs the PEP 517 `prepare_metadata_for_build_wheel` hook and, when the backend does not implement it, falls back to a full `build_wheel` — for a binary package that compiles the project, the most expensive thing the `deps` command does. Each `collect()` rebuilds the metadata from scratch and shares nothing, so the build is repeated whenever more than one would otherwise happen for the same tree: within one `deps add --candidates '...' --sync`, candidate probing collects each `metadata_extra` candidate (building the metadata to check `Provides-Extra`) and then `--sync` collects again; and across the separate `deps add ... --sync` commands run for each source, every metadata-derived source builds independently. The metadata is mandatory — there is no way to record metadata-derived dependencies without it — so the goal is not to avoid the build but to do it exactly once per tree.

Cache the built metadata text in a single file, `dist/metadata_cache`, under the working directory it was built from, so it is bound to that tree by location and goes away when `dist/` is cleaned. `parsed_metadata()` reads the cache when present and otherwise builds as before and writes it, so every `metadata` / `metadata_extra` collect and `--candidates` probe for the same tree shares one build — whether it used the cheap hook or the `build_wheel` fallback. The cache is always on; to force a rebuild, delete the file (or clean `dist/`).

Validate the metadata fully before trusting it, via `packaging.metadata` (`Metadata.from_email(validate=True)`), which checks every field against the core metadata specification rather than only `Requires-Dist`. A freshly built metadata is written to the cache only after it validates, so an invalid build result is never persisted, and a cache file that has become invalid (hand-edited or truncated) is rejected on read; the packaging errors are reported as a single error under the source's name.
